### ISSUE TITLE
More configurable plot outputs

### ISSUE THREAD

**Issue by half-adder** [ApfeldLab/pharynx_redox#20]
The user should be able to specify which plots they want outputted in the `settings.yaml` file.

So, the `output` section of the `settings.yaml` file might look something like:

```yaml
output:
    plots:
        single_animal_debug: True
        individual_profiles: True
        average_profiles: True
```
